name = "human-in-the-loop"
main = "./src/server.ts"
compatibility_date = "2025-02-21"
compatibility_flags = [
    "nodejs_compat",
    "nodejs_compat_populate_process_env",
  ]

assets = { directory = "public" }


[[durable_objects.bindings]]
name  = "HumanInTheLoop"
class_name = "HumanInTheLoop"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["HumanInTheLoop"]
