name: Prerelease

on:
  push:
    branches:
      - main

jobs:
  prerelease:
    if: ${{ github.repository_owner == 'cloudflare' }}
    timeout-minutes: 5
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3

      - run: npm install

      - name: Modify package.json version
        run: npx tsx .github/version-script.ts

      - name: Resolve workspace dependencies
        run: npx tsx .github/resolve-workspace-versions.ts

      - run: npm run build
      - run: npm run check
      - run: CI=true npm run test

      - run: npm publish --tag beta
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        working-directory: packages/agents

      - run: npm publish --tag beta
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        working-directory: packages/hono-agents
